baseURL = "https://sleepy-almeida-8cd155.netlify.com/"
languageCode = "en-us"
title = "Stellar Site"
theme = "hugoBase"


description = "I dont making web site"
  mainIcon = "/img/logo.png"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/SBootstrap"
[[params.social]]
    title = "github"
    url = "https://github.com/IronSummitMedia/startbootstrap"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/"
